"""Executor request and response schemas."""

from enum import Enum

from pydantic import BaseModel, Field


class ExecutorMode(str, Enum):
    """Executor operating modes."""

    NORMAL = "normal"
    REVISION = "revision"


class ExecutorField(str, Enum):
    """Executor artifact fields that can be generated or revised."""

    SUMMARY = "summary"
    REQUIRED_ACTIONS = "required_actions"
    CHECKLIST = "checklist"
    MISSING_INFORMATION = "missing_information"
    DRAFT_RESPONSE = "draft_response"


class ExecutorAction(BaseModel):
    """User-facing action generated by the executor."""

    title: str = Field(min_length=3)
    description: str = Field(min_length=5)
    due: str = Field(min_length=2)
    priority: str = Field(min_length=2)


class ExecutorChecklistItem(BaseModel):
    """Checklist item generated by the executor."""

    label: str = Field(min_length=3)
    completed: bool = False


class ExecutorOutput(BaseModel):
    """Strict schema for executor artifacts."""

    summary: str = Field(min_length=10)
    required_actions: list[ExecutorAction] = Field(min_length=1)
    checklist: list[ExecutorChecklistItem] = Field(min_length=1)
    missing_information: list[str] = Field(default_factory=list)
    draft_response: str = Field(min_length=10)
    provider_used: str = Field(min_length=1)
    mode: ExecutorMode
    revised_fields: list[ExecutorField] = Field(default_factory=list)


class ExecutorRevisionRequest(BaseModel):
    """Revision request constrained to explicitly flagged fields."""

    flagged_fields: list[ExecutorField] = Field(min_length=1)
    instructions: str = Field(min_length=5)
