"""Planner request and response schemas."""

from enum import Enum

from pydantic import BaseModel, Field


class PlannerDocumentType(str, Enum):
    """Document types the planner can classify."""

    DRC_01 = "DRC_01"
    GSTR_3A = "GSTR_3A"
    ASMT_10 = "ASMT_10"
    GST_INVOICE = "GST_INVOICE"
    TAX_REMINDER = "TAX_REMINDER"


class PlannerPriority(str, Enum):
    """Compliance priority generated by the planner."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class PlannerInput(BaseModel):
    """Structured input used to ask the planner for an action plan."""

    workflow_id: str
    document_text: str = Field(min_length=10)


class PlannerAction(BaseModel):
    """Action recommended by the planner."""

    title: str = Field(min_length=3)
    description: str = Field(min_length=5)
    due: str = Field(min_length=2)
    priority: PlannerPriority


class PlannerOutput(BaseModel):
    """Strict schema that every planner LLM response must satisfy."""

    document_type: PlannerDocumentType
    priority: PlannerPriority
    deadline: str = Field(min_length=2)
    objective: str = Field(min_length=10)
    required_actions: list[PlannerAction] = Field(min_length=1)
    missing_information: list[str] = Field(default_factory=list)
    risk_notes: list[str] = Field(default_factory=list)
    provider_used: str = Field(min_length=1)
